language: python
python:
  - "3.8"
before_install:
  - "pip install -U pip"
  - "python setup.py install"
install:
  - pip install -r requirements.txt
script:
  - pytest --cov-report term --cov=cassowary
after_success:
  - codecov
services:
  - mongodb
  - rabbitmq